### ISSUE TITLE
"Error: ENOTEMTY: directory not empty" when "gulp dev"

### ISSUE THREAD

**Issue by Fischaela** [morkro/FrontBook#9]
Using the `gulp dev` task sometimes throws an `Error: ENOTEMPTY: directory not empty` error. This may be caused because the tasks are not synchronous.

<img width="486" alt="Error: ENOTEMTY" src="https://cloud.githubusercontent.com/assets/3409561/13428936/87736ab4-dfb5-11e5-8109-0554cfa1503c.png">

**Comment by morkro** [comment]
Fixed with #10.
